project:
    type: website
    resources:
      - site/notebooks/
    output-dir: _site
    render:
        - site/index.qmd
        - site/sources.qmd
        - site/daily_journal.qmd
        - site/presentations/ai_usage.qmd

website:
    title: "Bachelor Thesis"
    repo-url: https://github.com/MadeInShineA/bachelor-thesis/
    repo-actions: [edit]
    navbar:
        left:
            - href: site/index.qmd
              text: Home
            - href: ./site/assets/report/bachelor-thesis.pdf
              text: Report
            - text: Notebooks
              menu:
                  - href: site/notebooks/npvr-simulation/index.html
                    text: NPVR Simulation
                  - href: site/notebooks/fuzzy-fmriprep-graph-metrics-analysis.html
                    text: Fuzzy fMRIPrep Graph Metrics Analysis
                  - href: site/notebooks/fuzzy-fmriprep-fc-matrices-analysis.html
                    text: Fuzzy fMRIPrep FC Matrices Analysis
                  - href: site/notebooks/fuzzy-pca-dim-reduction-analysis.html
                    text: Fuzzy PCA Dim Reduction Analysis

            - text: Presentations
              menu:
                  - href: site/presentations/ai_usage.qmd
                    text: AI usage presentation
            - href: site/sources.qmd
              text: Sources
            - href: site/daily_journal.qmd
              text: Daily Journal
        tools:
            - icon: github
              href: https://github.com/MadeInShineA/bachelor-thesis
              target: _blank
              text: Bachelor Thesis GitHub

    page-footer:
        left: |
            Made with [Quarto](https://quarto.org/){target="_blank"}
        center:
            - text: "Olivier Amacker Bachelor Thesis | © 2026"
        right:
            - icon: github
              href: https://github.com/MadeInShineA/bachelor-thesis
              target: _blank
              aria-label: Bachelor Thesis GitHub

format:
    html:
        respect-user-color-scheme: true
        toc: true
        toc-title: "Table of Content"
        toc-depth: 4
        theme:
            light: [cosmo, site/assets/style/theme.scss]
            dark: [cosmo, site/assets/style/dark_theme.scss]
        code-copy: true
        code-overflow: wrap
