---
title: Daily Journal
---

## 12.05.2026
- Initialized the main repository (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/470239d65c866045aa8a58641608495cf1a493e1){target="_blank"})

## 14.05.2026
- Initialized the report repository (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-report/commit/e98c34a0073836a643f68bc835485268b032624a){target="_blank"})

## 15.05.2026
- Welcome tour given by Masui san
- CBI meeting
- Created the main project website (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/f373c69ba41dea4fc163e97b9f497730e6441925){target="_blank"})

## 18.05.2026
- Updated the bibliography (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-report/commit/f1571617206d27923f4a6a124b14dbfdc362cfa1){target="_blank"})
- Created the source page on the main project website (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/6b3c7a96781bf5e99da97cd4dae5278d19656fbc){target="_blank"})
- Meeting with Ayumu and Okito san
- Went to Seika town hall to announce myself
- Fixed an issue where the bibliography inside the report submodule wasn't working on the main project website (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/9198310f30067ca20ebd0cfa825a8cc1101e8e97){target="_blank"})

## 19.05.2026
- Started the Alizadeh 2025 paper summary (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/e13ecdb5699655774f1c103d2e33d4ec3d16e9e6){target="_blank"} and [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/97f9c290f5ce773861aebee8620b55759a8c1978){target="_blank"})
- Updated the bibliography (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-report/commit/911e8a8f1cfbfdb74ae9126a31fff94edf1c07c7){target="_blank"} and [here](https://github.com/MadeInShineA/bachelor-thesis/commit/90f109b93c03812f0fb4904ae6a3ce45207bcd28){target="_blank"})
- Added daily journal page to main project website (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/a3d776cc8b37bcf7292a1d95ce17501c6bd07e9a){target="_blank"})

## 20.05.2026
- Added a flake.nix with uv to the project repository (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/decda97877bba7faad491713cdebfe66c907806a){target="_blank"})
- Finished Alizadeh 2025 paper summary v1 (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/ed8f0342a2b18430e95241bdd2942537c391178c){target="_blank"} and [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/813cd214d6a8bb164917ee544225c66983488ff8){target="_blank"})
- Created fuzzy fMRIPrep 25.2.5 Dockerfile (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/7c6345b4544e1e9211e943be586408d1ebefd952){target="_blank"})

## 21.05.2026
- Started the Andy’s Brain fMRIPrep tutorial
- Troubleshooted an issue regarding the fuzzy fMRIPrep container and fMRIPrep runs
    - Found that without the `--anat-only` flag the run would crash at the `skullstrip_first_pass` step
- Re read the Alizadeh 2025 paper summary to prepare for Monday meeting
- Started setting up the ATR VPN

## 22.05.2026
- Continued Andy’s Brain fMRIPrep tutorial
- Fixed the fuzzy fMRIPrep `skullstrip_first_pass` issue (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/bced0ddf22858b6d0876c1f7cfb45da696b220cf){target="_blank"})
    - What made the step fail was that `verificarlo` was outputting logs to `stderr`
- CBI meeting
- Fixed typos and bugs in the Alizadeh 2025 paper summary (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/bced0ddf22858b6d0876c1f7cfb45da696b220cf...1e7b4f2285222f87eecab43a5a632263e21e7846){target="_blank"})
- Updated the bibliography (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-report/commit/f4981eb709067e51e8d1962b051ef38e9adbc74a){target="_blank"})

## 25.05.2026
- Gave a last read to the Alizadeh 2025 paper summary for toray's meeting
- Meeting with Ayumu and Okito san
- Requested access for docker rights on the cluster
- Started writing slurm and local parallel computing scripts (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/0bb5b5224eec4ef0803ffa1160afd47d26455217){target="_blank"})

## 26.05.2026
- Troubleshooted the `multiprocessing.Manager()` issue
    - The Docker version was too old
- Published Docker image to DockerHub (see [here](https://hub.docker.com/repository/docker/madeinshinea/fuzzy-fmriprep/general){target="_blank"})
- Continued the slurm fuzzy fmriprep script (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/f21d42be379636bfca06e4396dae088797aa4877){target="_blank"})
- Continued the parallel fmriprep script (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/4be5b256e10b8f0e1675a8573e52ee5636410337){target="_blank"})
- Started the sequential_jobs script (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/9d33c11889ddecddee01970deb7f76f3e1f48599){target="_blank"})
- Tried to make some reproduction runs on the cluster unsuccessfully

## 27.05.2026
- Fixed the differen run scripts (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/c09bfc7480fde0ee9a4762be3ea2a0d830b45171){target="_blank"})
- Tested the run scripts and made fMRIPrep parallel test runs on several nodes
- Started the NPVR simulation notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/5374eb4f9acbe86ac1600c50c3fdbd19616d864f){target="_blank"} and notebook [here](./notebooks/npvr-simulation/){target="_blank"})

## 28.05.2026
- Finished the v1.0.0 of the NPVR simulation notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/16a7bf199faa5fb5dd275f31305a4768fff3b7ad...d09508233113ecfa0868be2c8c44a451564eb58e){target="_blank"} and notebook [here](./notebooks/npvr-simulation/){target="_blank"})
- Added 2 utils nu script to get the subjects by common laboratory and their filename (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/d09508233113ecfa0868be2c8c44a451564eb58e...5fa350c0aa0cb07e8290fd81db25412f926acb5e){target="_blank"})

## 29.05.2026
- Wrote the necessary scripts to run the `parallel_jobs.sh` script with PBS (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/aad44cb81c7446dba313b62ffe234d27ad938012){target="_blank"})
- CBI meeting
- Fixed the `parallel_jobs.sh` directory creation and added a step to pull the Docker image if not present (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/fad84ed4dc2310735a5fae8433c3f39b792d7874){target="_blank"})
- Modified the PBS `run_parallel_jobs.sh` script to add a metadata file creation and fixed the parallel jobs work directory name (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/5be6e1a8352a535569567a28e7cc3a97097cad09){target="_blank"})
- Fixed the output filenames the `get_sub_filename_by_common_lab.nu` script (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/7849fa28b55a207a739e375a1f321105bd20007d){target="_blank"})
- Fixed different issues in the pbs `run_parallel_jobs.sh` script (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/de3c918ecd49532ab0dfd1b266b8cb8fbfdfdc2f){target="_blank"})
- Ran 15 fMRIPrep runs on the cluster nodes

## 01.06.2026
- Informed myself on the connectivity analysis pipeline
- Began a connectivity analysis pipeline overview document (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/e0a59fbddbba2c8a19306226504e0c8885f8adc5){target="_blank"})
- Meeting with Prof. Esteban
- Opened an issue in the Numerical-Variability-of-functional-MRI-Graph-Measures repository (see [here](https://github.com/mina94az/Numerical-Variability-of-functional-MRI-Graph-Measures/issues/1){target="_blank"})
- Added a github action to the report repository to automatically release the report (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-report/compare/ef4e06fbe1e6947c71e48210d844824560f44632...899d2723dc6e335c784a7123a6b2712a31385958){target="_blank"})
- Add the Download Thesis menu button

## 02.06.2026
- Started the `fuzzy_fmriprep_graph_metrics_analysis` marimo notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/17911fc13bddd52d75fba31f802fdda7fe08e273...b01a0752d46dd9e3a32a20caa48051357c69b393){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-graph-metrics-analysis.html){target="_blank"})
    - Computed some FC matrices (currently very slow)

## 03.06.2026
- Continued the `fuzzy_fmriprep_graph_metrics_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/b01a0752d46dd9e3a32a20caa48051357c69b393...28f9025921128a200c346fb5ae39652f70b1adf4){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-graph-metrics-analysis.html){target="_blank"})
    - Changed the FC matrices computations to be in parallel
    - Added threshold graphs to the notebook
- Started a first draft of the project Gantt diagram (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/62409857692cf7e39719ddab056908460ad6668f){target="_blank"} and page [here](./index.qmd){target="_blank"})

## 04.06.2026
- Continued the `fuzzy_fmriprep_graph_metrics_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/28f9025921128a200c346fb5ae39652f70b1adf4...d42dd0f62b7675d350552e853d33d7b3595b75ad){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-graph-metrics-analysis.html){target="_blank"})
    - Computed graph metrics on the thresholded graphs
    - Computed and plotted NPVR
- Contributed to the report thesis repository (see PR [here](https://github.com/ISC-HEI/isc-hei-typst-templates/pull/30){target="_blank"})
- Began the report cover page (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-report/compare/899d2723dc6e335c784a7123a6b2712a31385958...8f1da9ee6585c68c6d5a1c23861e8215bd425060){target="_blank"})

## 05.06.2026
- Made the `fuzzy_fmriprep_graph_metrics_analysis` notebook save some of it's output (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/d42dd0f62b7675d350552e853d33d7b3595b75ad...1445c030162b51fdc764d74dbdb00edbd21a24d8){target="_blank"} and output [here](https://github.com/MadeInShineA/bachelor-thesis-project/tree/6567b64fac5efeb8ff2186c69e7c8af829bcecb1/res/fuzzy-fmriprep-analysis){target="_blank"})
    - FC matrices
    - Threshold graph plot
    - Graph metrics
    - NPVR variation plots
- Ran several versions of the connectivity analysis pipeline (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/6567b64fac5efeb8ff2186c69e7c8af829bcecb1){target="_blank"})
- CBI meeting
- Fixed a bibliography issue in the school template (see PR [here](https://github.com/ISC-HEI/isc-hei-typst-templates/pull/31){target="_blank"})
- Started the report abstract (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-report/commits/276a7694a85af77cd13e1facb2bc0db4b7e08c76/){target="_blank"})

## 08.06.2026
- Continued the report abstract and acknowledgment (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-report/compare/276a7694a85af77cd13e1facb2bc0db4b7e08c76...55c7ee5db687d168746c4564e999ddb9ae84c19d){target="_blank"})
- Fixed project python dependencies
- Continued the `fuzzy_fmriprep_graph_metrics_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/c780e536fcf3e26cfdbfba960c0ee70f4cd55f78...1bb90ead7afd09bef632c46f4524a4ae957290a2){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-graph-metrics-analysis.html){target="_blank"})
    - Added the NVPR per brain region plots
    - Fixed an issue in the `calculate_npvr_data ` function
    - Added NPVR calculation details

## 09.06.2026
- Continued the `fuzzy_fmriprep_graph_metrics_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/1bb90ead7afd09bef632c46f4524a4ae957290a2...59a523dab8d9a4517e8795d58771b380127d1893){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-graph-metrics-analysis.html){target="_blank"})
    - Made the graph metric calculation run in parallel
    - Fixed the v1 run metadata
- Added QOL to the `fuzzy_fmriprep_graph_metrics_analysis` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/b53d209849916bc370872ee9bd4d55d54697866f){target="_blank"})
- Changed the Docker run command inside `run_parallel_jobs.sh` to add replicabiliy parameters (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/61d78e56724e576057ba5166af94058ce643e1d7){target="_blank"})
- Meeting with Ayumu and Okito san

## 10.06.2026
- Changed the Docker run command inside `run_parallel_jobs.sh` to add cifti output (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/d2b306d0c2b8c6f059ce64b6e343a9d9e9c01460){target="_blank"})
- Cleaned up  the `fuzzy_fmriprep_graph_metrics_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/d2b306d0c2b8c6f059ce64b6e343a9d9e9c01460...caa41c494b3c2d303ce5317f14924bdd4fce9bb1){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-graph-metrics-analysis.html){target="_blank"})
    - Reversed the color of the threshold plots
    - Made the notebook reusable
    - Polished the overall code
    - Renamed the notebook
    - Chanded the output paths
- Started the `fuzzy_fmriprep_fc_matrices_analysis` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commits/5b9a099adc9de4b03b4d30d2f4fe8074ea2f08da/){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-fc-matrices-analysis.html){target="_blank"})

## 11.06.2026
- Continued the `fuzzy_fmriprep_fc_matrices_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/3eb768777e4af14dce517ca11930e15fd05f12d0...c27b6535560645255dcb732771104ea455be6d77){target="_blank"} and notebook [here](./notebooks/fuzzy-fmriprep-fc-matrices-analysis.html){target="_blank"})
    - Added different plots from the previous FC matrices, as the current one are still running
- Meeting with Prof. Esteban and Phd. Chatelain

## 12.06.2026
- Looked into what to do with the FC matrices extraction MCA perturbation
- Started re-reading [this paper](https://pmc.ncbi.nlm.nih.gov/articles/PMC12869322/){target="_blank"})
- Wrote a small script to test OS numerical variability

## 15.06.2026
- Started the `fuzzy_pca_dim_reduction_analysis` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/509f683e92b3c643cdde24638d4b52d7753008c5){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
- Contributed to the PCA dimentionality reduction github repository (see PR [here](https://github.com/Ayumu722/pca-based-feature-extraction/pull/1){target="_blank"})
    - Transformed the project into a Python package

## 16.06.2026
- Continued the `fuzzy_pca_dim_reduction_analysis` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commits/3758cad1cf11f818dfcf9d04014c8b2b94425dcc/){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
    - Added the PCA feature plot for the wanted metrics
- Contributed to the PCA dimentionality reduction github repository (see PR [here](https://github.com/Ayumu722/pca-based-feature-extraction/pull/2){target="_blank"})
    - Improved the PCA feature plot title and added x and y labels

## 17.06.2026
- Continued the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/3758cad1cf11f818dfcf9d04014c8b2b94425dcc...e3727228cb76f6f998ba7e09bc2ac2f3425dbf18){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
    - Made the PCA feature extraction more modular
    - Started plotting the PCA FC MDD vs HC brains

## 18.06.2026
- Continued the `fuzzy_pca_dim_reduction_analysis` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/ffa0f531d8f25506e9208813310a18777b6cbeb0){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
    - Started analyzing the `BMB` dataset
- Realized a mistake in the current `fuzzy_pca_dim_reduction_analysis` notebook analysis pipeline
    - I only plotted the FC that were unique between all the MDD vs HC PC instead of plotting all the FC of the selected PC

## 19.06.2026
- Continued the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/ffa0f531d8f25506e9208813310a18777b6cbeb0...2c6aedf3927659dcb4b3ad5abb02ea651bc0db47){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
    - Corrected the analysis pipeline
    - Finished the first version of the notebook reproduction part.

## 22.06.2026
- Finished the reproduction part of the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/2c6aedf3927659dcb4b3ad5abb02ea651bc0db47...53fa96ce8ce929ef0bc5d3e70b4b54100d141c4b){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
    - Fixed an issue where the parcellation regions were not the correct one
    - Fixed an issue with the FC matrices element indexes
    - Improved the FC brain plot

## 23.06.2026
- Started the FC matrix extraction in the `fuzzy_pca_dim_reduction_analysis` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/c5573eda698650b7c49631fa22789b3b84becabd){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
    - Only added the basic pipeline until the extraction
- Started reading the [TS harmonization paper](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000042){target="_blank"}
- Tried to create a fuzzy numpy docker container

## 24.06.2026
- Finished reading the [TS harmonization paper](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000042){target="_blank"}
- Read the [TS inter-site differences](https://www.nature.com/articles/s41380-025-03134-6){target="_blank"}

## 25.06.2026
- Finished the regular FC matrices extraction part of the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/d3a55cb5d9b391b88bb3f287229ff26ca5805e1d){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})

## 26.06.2026
- Fixed a mistake in the comparison of the extracted FC matrices and the harmonized ones in the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/bfefa775d6fc55240b234fe9f76de6ebf605c6cf){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
- Started the harmonization procedure in the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/549dd0ec277a8c7884ffc30a9075dbe69b94ede2){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})

## 29.06.2026
- Continued the harmonization procedure in the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/4519ab0dbdeee991ad498636ec8c24ace4950e14){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
- Installed a local LLM ([this model](https://huggingface.co/unsloth/Qwen3.5-4B-GGUF){target="_blank"} and [Cherry studio](https://github.com/cherryhq/cherry-studio){target="blank"} to help troubleshooting

## 30.06.2026
- Looked into how the harmonization was done mathematically
- Started a [Excalidraw](https://excalidraw.com/){target="_blank"} schema (see [here](https://excalidraw.com/#json=NDviFkoyqdx0cjhuDitnE,kjovnsS2aLeS_UgxsBofQw){target="_blank"}
- Continued the harmonization procedure in the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/1bbf5ec8ab2cfb5d6120ca6cd352d686a045a842){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})

## 01.06.2026
- Finished writing the code for the harmonization in the `fuzzy_pca_dim_reduction_analysis` notebook (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/7547251d4a84d59de1a0f58fb846e2068095e3d5){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})
    - It still needs testing

## 02.06.2026
- Fixed and verified the harmonization code in the `fuzzy_pca_dim_reduction_analysis` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/dfafeb13dd333285092d1a23a01acbc43462465d){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})

## 03.06.2026
- Ran a first fuzzy PCA dimentionality reduction analysis on 2 runs, with the pipeline used for the reproduction (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/commit/20ed022f5d819fe1446b9711575bfbc59ade3cdb){target="_blank"} and notebook [here](./notebooks/fuzzy-pca-dim-reduction-analysis.html){target="_blank"})

## 06.07.2026
- Ran 100 fuzzy PCA dimentionality reduction, made quite in depth analysis and started BMB extraction (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/20ed022f5d819fe1446b9711575bfbc59ade3cdb...65941764529ec023d383d8cc3d3aa97d20ae6eb6){target="_blank"})

## 07.07.2026
- Created my Ai usage presentation slides (see slides [here](./presentations/ai_usage.qmd))
- Finished gathering the BMB subjects and launched 2 fuzzy extraction runs

## 08.07.2026
- Attended the AI usage workshop, and presented my view
- Finished the BMB harmonization and started 10 new runs (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/20ed022f5d819fe1446b9711575bfbc59ade3cdb...65941764529ec023d383d8cc3d3aa97d20ae6eb6){target="_blank"})

## 09.07.2026
- Updated the different README
- Continued the BMB analysis (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/8938a7c4da7d223477a0b6a02ee36ea314753cb3...b39e611b170d32344b992e3d56b237b77c761b59){target="_blank"})
- Cleaned the `npvr_simulation` notebook (see commit [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/a02ee6bcdf34a9972e4a258d9e5543f348d46998...87dd38ec840b5a250075c72e1a75a877cec545fe){target="_blank})

## 10.07.2026
- Updated the website home page (see commit [here](https://github.com/MadeInShineA/bachelor-thesis/commit/30db66bdf617f41140ce4f6d99e9ee5fe3741084){target="_blank"} and page [here](./index.qmd){target="_blank"})
- Cleaned the different notebooks, README, etc... for the first submission (see commits [here](https://github.com/MadeInShineA/bachelor-thesis-project/compare/87dd38ec840b5a250075c72e1a75a877cec545fe...9df99a1591ae73644c04be9ffd8bb6f65353dbff){target="_blank"})
